[client]
showErrorDetails = true
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
